import { useMemo, useRef, useState } from 'react'
import { adCopyVariants, adCreativeVariants, assetLibrary, campaignTemplates, campaigns, dashboardMockService, leadRecords, metaConnection, optimizationHistory, optimizationRecommendations } from './dashboardMockData.js'
import { AdPreview, Badge, Button, CreativeArt, EmptyState, Field, Icon, Modal, PageIntro, Spinner, Toggle } from './dashboardUI.jsx'

function MetaAccountStrip({ connected, onManage }) {
  return (
    <section className={`db-meta-strip db-card ${connected ? '' : 'disconnected'}`}>
      <div className="db-meta-symbol">∞</div><div><span className="db-eyebrow">Meta ads connection</span><h3>{connected ? metaConnection.account.name : 'No Meta Ads account connected'}</h3><p>{connected ? `${metaConnection.page.name} · ${metaConnection.account.currency} · ${metaConnection.account.status}` : 'Connect an account to build and manage real campaigns later.'}</p></div>
      {connected ? <><div className="db-meta-health"><i /> Connected</div><Field label="Reporting"><select defaultValue="last14"><option value="today">Today</option><option value="last7">Last 7 days</option><option value="last14">Last 14 days</option><option value="last30">Last 30 days</option></select></Field></> : null}
      <Button variant="secondary" icon="settings" onClick={onManage}>{connected ? 'Manage' : 'Connect Meta'}</Button>
    </section>
  )
}

const AD_STEPS = ['Promote', 'Build', 'Review', 'Launch']
const PLACEMENTS = ['Facebook Feed', 'Instagram Feed', 'Instagram Stories', 'Facebook Reels', 'Instagram Reels']

function AdStepper({ stage }) {
  const active = stage === 4 ? 4 : stage
  return <ol className="db-flow-stepper ad">{AD_STEPS.map((label, index) => <li className={index < active ? 'done' : index === active ? 'active' : ''} key={label}><span>{index < active ? <Icon name="check" size={13} /> : index + 1}</span><b>{label}</b>{index < AD_STEPS.length - 1 && <i />}</li>)}</ol>
}

function CampaignTarget({ form, setForm, onBuild, busy }) {
  const kinds = [
    ['brand', 'My brand', 'Use saved brand context and your primary website.', 'target'],
    ['custom', 'Custom offer', 'Provide a campaign offer and destination.', 'file'],
    ['post', 'Facebook post', 'Promote an existing connected Page post.', 'content'],
  ]
  const togglePlacement = (item) => setForm({ ...form, placements: form.placements.includes(item) ? form.placements.filter((value) => value !== item) : [...form.placements, item] })
  return <div className="db-ad-target-grid">
    <div className="db-ad-target-main">
      <section className="db-card"><div className="db-section-heading"><span><Icon name="target" size={18} /></span><div><h2>What are you promoting?</h2><p>The campaign stays fully editable before anything is sent to Meta.</p></div><Badge tone="blue">Objective · Leads</Badge></div><div className="db-choice-grid three">{kinds.map(([id, title, body, icon]) => <button className={form.kind === id ? 'active' : ''} onClick={() => setForm({ ...form, kind: id })} key={id}><span><Icon name={icon} size={19} /></span><b>{title}</b><small>{body}</small>{form.kind === id && <i><Icon name="check" size={13} /></i>}</button>)}</div>
        {form.kind === 'custom' && <div className="db-form-grid two"><Field label="Offer title"><input value={form.offer} onChange={(event) => setForm({ ...form, offer: event.target.value })} /></Field><Field label="Landing-page URL"><input value={form.url} onChange={(event) => setForm({ ...form, url: event.target.value })} placeholder="https://…" /></Field></div>}
        {form.kind === 'post' && <div className="db-promotable-posts">{['Move with purpose', 'Behind the blend'].map((post, index) => <button className={form.post === post ? 'active' : ''} onClick={() => setForm({ ...form, post })} key={post}><CreativeArt palette={index ? 'orange' : 'lime'} theme={post.toUpperCase().replace(' ', ' / ')} compact /><span><b>{post}</b><small>Published Sep {24 - index}</small></span>{form.post === post && <Icon name="check" size={15} />}</button>)}</div>}
        <Field label="Campaign brief (optional)" hint="Share the offer, audience, proof points, or constraints that matter most."><textarea rows="4" value={form.brief} onChange={(event) => setForm({ ...form, brief: event.target.value })} /></Field>
      </section>
      <section className="db-card"><div className="db-section-heading compact"><span><Icon name="settings" size={18} /></span><div><h2>Generation options</h2><p>Shape the first plan. You can refine every setting later.</p></div></div><div className="db-form-grid two"><Field label="Duration"><select value={form.duration} onChange={(event) => setForm({ ...form, duration: event.target.value })}>{[7, 14, 30, 60].map((days) => <option value={days} key={days}>{days} days</option>)}</select></Field><Field label="Copy variants"><select value={form.variants} onChange={(event) => setForm({ ...form, variants: event.target.value })}>{[1, 2, 3, 4, 5].map((count) => <option value={count} key={count}>{count} variants</option>)}</select></Field><Field label="Starting template"><select value={form.template} onChange={(event) => setForm({ ...form, template: event.target.value })}><option value="">Generate fresh</option>{campaignTemplates.map((item) => <option key={item.id}>{item.name}</option>)}</select></Field><Field label="Target countries"><input value={form.countries} onChange={(event) => setForm({ ...form, countries: event.target.value })} /></Field><Toggle checked={form.aiImages} onChange={(value) => setForm({ ...form, aiImages: value })} label="AI-styled images" hint="Add fresh visual directions." /><Toggle checked={form.interests} onChange={(value) => setForm({ ...form, interests: value })} label="Interest targeting" hint="Propose relevant audience interests." /></div><Field label="Placements"><div className="db-select-pills">{PLACEMENTS.map((item) => <button className={form.placements.includes(item) ? 'active' : ''} onClick={() => togglePlacement(item)} key={item}>{form.placements.includes(item) && <Icon name="check" size={12} />}{item}</button>)}</div></Field></section>
    </div>
    <aside className="db-ad-target-aside"><section className="db-card"><span className="db-eyebrow"><Icon name="spark" size={14} /> Brand rules</span><h3>Adcraft Studio</h3><p>Creative strategy · confident, concise, and human.</p><Field label="Tone"><input value={form.tone} onChange={(event) => setForm({ ...form, tone: event.target.value })} /></Field><Field label="Never use"><input value={form.banned} onChange={(event) => setForm({ ...form, banned: event.target.value })} /></Field><Field label="Must include"><input value={form.required} onChange={(event) => setForm({ ...form, required: event.target.value })} /></Field><div className="db-form-grid two"><Toggle checked={form.emojis} onChange={(value) => setForm({ ...form, emojis: value })} label="Emojis" /><Toggle checked={form.hashtags} onChange={(value) => setForm({ ...form, hashtags: value })} label="Hashtags" /></div><Button variant="secondary" className="full" icon="check" onClick={() => {}}>Save brand rules</Button></section><Button className="full large" icon="spark" disabled={busy || (form.kind === 'custom' && (!form.offer || !form.url)) || (form.kind === 'post' && !form.post)} onClick={onBuild}>Build my campaign</Button><p className="db-safe-note"><Icon name="info" size={14} /> Nothing goes live without your approval.</p></aside>
  </div>
}

function CampaignReview({ plan, setPlan, copies, setCopies, creatives, setCreatives, onLaunch, onReset, launching }) {
  const fileInput = useRef(null)
  const selectedCopies = copies.filter((item) => item.selected)
  const selectedCreatives = creatives.filter((item) => item.selected)
  const adCount = Math.min(6, selectedCopies.length * selectedCreatives.length)
  const patchCopy = (id, patch) => setCopies((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item))
  const upload = (file) => { if (!file) return; setCreatives((current) => [...current, { id: `upload-${Date.now()}`, name: file.name, kind: 'Uploaded', palette: 'mono', theme: 'YOUR / CREATIVE', imageUrl: URL.createObjectURL(file), selected: true }]) }
  const addCopy = async () => { const next = { ...adCopyVariants[2], id: `copy-${Date.now()}`, selected: true, angle: 'Fresh angle' }; setCopies((current) => [...current, next]) }
  const addCreative = () => setCreatives((current) => [...current, { ...adCreativeVariants[2], id: `creative-${Date.now()}`, selected: true, name: 'New visual direction' }])
  const ready = adCount > 0 && plan.form.questions.length > 0 && plan.form.privacy.startsWith('http') && Number(plan.budget) >= 5
  return <div className="db-campaign-review">
    <div className="db-review-head db-card"><div><Badge>Ready to review</Badge><h2>Summer Movement · Lead Campaign</h2><p>Generated from your brand, offer, and connected Page.</p></div><div><strong>{adCount}</strong><span>ads selected</span></div></div>
    <div className="db-campaign-review-grid"><div className="db-review-stack">
      <section className="db-card"><div className="db-card-title"><div><span>01</span><h3>Copy angles <small>{selectedCopies.length} selected</small></h3></div><Button variant="soft" icon="refresh" onClick={addCopy}>Another angle</Button></div><div className="db-copy-variants">{copies.map((copy) => <article className={copy.selected ? 'selected' : ''} key={copy.id}><button className="db-select-check" onClick={() => patchCopy(copy.id, { selected: !copy.selected })}>{copy.selected && <Icon name="check" size={13} />}</button><Badge tone="blue">{copy.angle}</Badge><Field label="Primary text"><textarea rows="4" value={copy.primary} onChange={(event) => patchCopy(copy.id, { primary: event.target.value })} /></Field><Field label="Headline"><input value={copy.headline} onChange={(event) => patchCopy(copy.id, { headline: event.target.value })} /></Field><Field label="Call to action"><select value={copy.cta} onChange={(event) => patchCopy(copy.id, { cta: event.target.value })}><option>SIGN_UP</option><option>LEARN_MORE</option><option>SHOP_NOW</option><option>GET_QUOTE</option></select></Field><button className="db-text-action" onClick={() => patchCopy(copy.id, { primary: `${copy.primary} Discover the difference today.` })}><Icon name="spark" size={13} /> Rewrite this angle</button></article>)}</div></section>
      <section className="db-card"><div className="db-card-title"><div><span>02</span><h3>Creative directions <small>{selectedCreatives.length} selected</small></h3></div><div><Button variant="ghost" icon="upload" onClick={() => fileInput.current?.click()}>Upload</Button><Button variant="soft" icon="spark" onClick={addCreative}>Generate</Button><input ref={fileInput} type="file" accept="image/*" hidden onChange={(event) => upload(event.target.files?.[0])} /></div></div><div className="db-creative-variants">{creatives.map((creative) => <article className={creative.selected ? 'selected' : ''} key={creative.id}><button onClick={() => setCreatives((current) => current.map((item) => item.id === creative.id ? { ...item, selected: !item.selected } : item))}><CreativeArt palette={creative.palette} theme={creative.theme} imageUrl={creative.imageUrl} compact /><i>{creative.selected && <Icon name="check" size={13} />}</i></button><div><b>{creative.name}</b><Badge tone="gray">{creative.kind}</Badge><span><button onClick={() => setCreatives((current) => current.map((item) => item.id === creative.id ? { ...item, palette: item.palette === 'lime' ? 'blue' : 'lime' } : item))}>Brand</button><button onClick={() => setCreatives((current) => current.map((item) => item.id === creative.id ? { ...item, palette: 'orange' } : item))}>Restyle</button></span></div></article>)}</div></section>
      <Button variant="ghost" icon="refresh" onClick={onReset}>Start over</Button>
    </div><aside className="db-review-sidebar">
      {selectedCopies[0] && selectedCreatives[0] && <AdPreview headline={selectedCopies[0].headline} primary={selectedCopies[0].primary} cta={selectedCopies[0].cta} palette={selectedCreatives[0].palette} theme={selectedCreatives[0].theme} />}
      <section className="db-card"><h3><Icon name="target" size={17} /> Audience</h3><p>United States · Advantage+ audience</p><div className="db-form-grid two"><Field label="Minimum age"><input type="number" min="18" max="65" value={plan.ageMin} onChange={(event) => setPlan({ ...plan, ageMin: event.target.value })} /></Field><Field label="Maximum age"><input type="number" min="18" max="65" value={plan.ageMax} onChange={(event) => setPlan({ ...plan, ageMax: event.target.value })} /></Field></div><Field label="Placements"><div className="db-select-pills small">{PLACEMENTS.map((item) => <button className={plan.placements.includes(item) ? 'active' : ''} onClick={() => setPlan({ ...plan, placements: plan.placements.includes(item) ? plan.placements.filter((value) => value !== item) : [...plan.placements, item] })} key={item}>{item}</button>)}</div></Field></section>
      <section className="db-card"><h3><Icon name="wallet" size={17} /> Budget & schedule</h3><div className="db-form-grid two"><Field label="Daily budget (USD)"><input type="number" min="5" value={plan.budget} onChange={(event) => setPlan({ ...plan, budget: event.target.value })} /></Field><Field label="Duration (days)"><input type="number" min="3" max="90" value={plan.duration} onChange={(event) => setPlan({ ...plan, duration: event.target.value })} /></Field></div><p className="db-helper">Estimated total: ${(Number(plan.budget) * Number(plan.duration)).toLocaleString()} · America/New_York</p></section>
      <section className="db-card db-lead-form-builder"><h3><Icon name="file" size={17} /> Lead form</h3><Field label="Form name"><input value={plan.form.name} onChange={(event) => setPlan({ ...plan, form: { ...plan.form, name: event.target.value } })} /></Field><Field label="Privacy policy URL"><input value={plan.form.privacy} onChange={(event) => setPlan({ ...plan, form: { ...plan.form, privacy: event.target.value } })} /></Field><Field label="Thank-you message"><textarea rows="3" value={plan.form.thanks} onChange={(event) => setPlan({ ...plan, form: { ...plan.form, thanks: event.target.value } })} /></Field><div className="db-question-list"><span>Questions</span>{plan.form.questions.map((question, index) => <div key={`${question}-${index}`}><input value={question} onChange={(event) => setPlan({ ...plan, form: { ...plan.form, questions: plan.form.questions.map((item, itemIndex) => itemIndex === index ? event.target.value : item) } })} /><button disabled={plan.form.questions.length === 1} onClick={() => setPlan({ ...plan, form: { ...plan.form, questions: plan.form.questions.filter((_, itemIndex) => itemIndex !== index) } })}><Icon name="trash" size={14} /></button></div>)}<Button variant="ghost" icon="plus" onClick={() => setPlan({ ...plan, form: { ...plan.form, questions: [...plan.form.questions, 'New question'] } })}>Add question</Button></div></section>
      <section className="db-card db-launch-settings"><h3><Icon name="send" size={17} /> Launch</h3><div className="db-choice-grid two compact"><button className={plan.goLive ? 'active' : ''} onClick={() => setPlan({ ...plan, goLive: true })}><b>Go live</b><small>Submit active</small></button><button className={!plan.goLive ? 'active' : ''} onClick={() => setPlan({ ...plan, goLive: false })}><b>Save paused</b><small>Activate later</small></button></div><Toggle checked={plan.optimize} onChange={(value) => setPlan({ ...plan, optimize: value })} label="Optimize for me" hint="Apply guarded nightly checks." /><Field label="Save as template (optional)"><input value={plan.templateName} onChange={(event) => setPlan({ ...plan, templateName: event.target.value })} /></Field>{!ready && <p className="db-warning">Select copy and images, keep a lead-form question, use a valid privacy URL, and meet the minimum budget.</p>}<Button className="full large" icon="send" disabled={!ready || launching} onClick={onLaunch}>{launching ? 'Launching…' : `Launch ${adCount} ad${adCount === 1 ? '' : 's'}`}</Button></section>
    </aside></div>
  </div>
}

function LaunchComplete({ result, onAgain, onCampaigns }) {
  return <section className="db-card db-launch-complete"><span><Icon name="check" size={31} /></span><Badge>Created successfully</Badge><h2>Campaign created in Meta.</h2><p>Summer Movement · {result.ads} ads · Active</p><div className="db-created-objects"><div><span>Lead form</span><b>{result.leadFormId}</b></div><div><span>Campaign</span><b>{result.campaignId}</b></div><div><span>Ad set</span><b>{result.adSetId}</b></div><div><span>Ads</span><b>{result.ads}</b></div></div><div><Button variant="secondary" icon="plus" onClick={onAgain}>Create another</Button><Button icon="campaigns" onClick={onCampaigns}>View campaigns</Button></div></section>
}

export function AdsStudio({ connected, onManage, notify, onGo }) {
  const initialForm = { kind: 'brand', offer: 'Summer Movement Collection', url: 'https://adcraft.co/summer', post: '', brief: 'Generate high-intent leads for the new collection. Lead with light materials, everyday movement, and confident design.', duration: '14', variants: '3', template: '', countries: 'United States', aiImages: true, interests: false, placements: [...PLACEMENTS], tone: 'Confident, concise, human', banned: 'cheap, guaranteed', required: 'Designed to move', emojis: false, hashtags: false }
  const initialPlan = { ageMin: 22, ageMax: 54, placements: [...PLACEMENTS], budget: 45, duration: 14, goLive: true, optimize: true, templateName: '', form: { name: 'Summer Movement · Early Access', privacy: 'https://adcraft.co/privacy', thanks: 'Thanks — your early-access details are on the way.', questions: ['Full name', 'Email', 'Phone number', 'When are you looking to purchase?'] } }
  const [stage, setStage] = useState(0)
  const [form, setForm] = useState(initialForm)
  const [plan, setPlan] = useState(initialPlan)
  const [copies, setCopies] = useState(adCopyVariants)
  const [creatives, setCreatives] = useState(adCreativeVariants)
  const [result, setResult] = useState(null)
  const [busy, setBusy] = useState(false)
  const build = async () => { setStage(1); setBusy(true); const generated = await dashboardMockService.createCampaignPlan(form); setCopies(generated.copies); setCreatives(generated.creatives); setBusy(false); setStage(2) }
  const launch = async () => { setStage(3); setBusy(true); const response = await dashboardMockService.launchCampaign({ form, plan, copies, creatives }); setResult(response); setBusy(false); setStage(4); notify('Campaign and lead form created in demo mode.') }
  const reset = () => { setStage(0); setResult(null); setCopies(adCopyVariants); setCreatives(adCreativeVariants); setPlan(initialPlan) }
  return <div className="db-page"><PageIntro eyebrow="Campaign studio" icon="ads" title="Build a lead campaign from one clear idea." description="Strategy, copy, creative, audience, lead form, and optimization—assembled, editable, and ready for Meta." /><MetaAccountStrip connected={connected} onManage={onManage} />
    {!connected ? <EmptyState icon="link" title="Connect Meta Ads to begin" body="Campaign creation needs an ad account and Facebook Page identity." action={<Button icon="link" onClick={onManage}>Connect Meta Ads</Button>} /> : <><AdStepper stage={stage} />{stage === 0 && <CampaignTarget form={form} setForm={setForm} onBuild={build} busy={busy} />}{stage === 1 && <section className="db-card db-job-card"><Spinner label="Building your campaign…" progress={78} /><div className="db-job-steps">{['Brand', 'Offer', 'Audience', 'Copy', 'Visuals', 'Assemble'].map((item, index) => <span className={index < 4 ? 'done' : index === 4 ? 'active' : ''} key={item}><i>{index < 4 ? <Icon name="check" size={12} /> : index + 1}</i>{item}</span>)}</div><p>You can safely leave this screen. The generated plan is not published to Meta.</p></section>}{stage === 2 && <CampaignReview plan={plan} setPlan={setPlan} copies={copies} setCopies={setCopies} creatives={creatives} setCreatives={setCreatives} onLaunch={launch} onReset={reset} launching={busy} />}{stage === 3 && <section className="db-card db-job-card"><Spinner label="Creating your Meta campaign…" progress={86} /><div className="db-job-steps">{['Lead form', 'Campaign', 'Ad set', 'Ads', 'Optimize', 'Done'].map((item, index) => <span className={index < 4 ? 'done' : index === 4 ? 'active' : ''} key={item}><i>{index < 4 ? <Icon name="check" size={12} /> : index + 1}</i>{item}</span>)}</div></section>}{stage === 4 && result && <LaunchComplete result={result} onAgain={reset} onCampaigns={() => onGo('campaigns')} />}</>}
  </div>
}

export function CampaignsView({ connected, onManage, notify }) {
  const [items, setItems] = useState(campaigns)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [sort, setSort] = useState('spend')
  const [detail, setDetail] = useState(null)
  const visible = useMemo(() => items.filter((item) => (status === 'all' || item.status === status) && item.name.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : b[sort] - a[sort]), [items, query, status, sort])
  const total = items.reduce((sum, item) => sum + item.spend, 0)
  const toggle = (campaign) => { const next = campaign.status === 'paused' ? 'active' : 'paused'; setItems((current) => current.map((item) => item.id === campaign.id ? { ...item, status: next, delivery: next === 'active' ? 'Healthy' : 'Paused' } : item)); setDetail((current) => current?.id === campaign.id ? { ...current, status: next } : current); notify(`${campaign.name} ${next === 'active' ? 'resumed' : 'paused'}.`) }
  return <div className="db-page"><PageIntro eyebrow="Meta campaigns" icon="campaigns" title="Know what is working. Act quickly." description="Campaign delivery and results across the selected reporting window." actions={<Button variant="secondary" icon="refresh" onClick={() => notify('Campaign data refreshed.')}>Refresh</Button>} /><MetaAccountStrip connected={connected} onManage={onManage} />
    {!connected ? <EmptyState icon="campaigns" title="No campaign data yet" body="Connect Meta Ads to load campaigns and performance." /> : <><div className="db-metric-grid four"><article className="db-card"><span>Spend</span><strong>${total.toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong><small>+12.4% vs previous</small></article><article className="db-card"><span>Leads</span><strong>{items.reduce((sum, item) => sum + item.leads, 0)}</strong><small>+24.1% vs previous</small></article><article className="db-card"><span>Average CPL</span><strong>$8.74</strong><small className="good">↓ 9.6% improvement</small></article><article className="db-card"><span>Click-through rate</span><strong>3.09%</strong><small>+0.4 percentage points</small></article></div>
      <section className="db-card db-data-section"><header><div><h2>Campaigns</h2><p>Live Meta objects with performance from the last 14 days.</p></div><div className="db-view-switch"><button className="active">Campaigns</button><button onClick={() => notify('Ad set drill-down is represented in campaign details.')}>Ad sets</button><button onClick={() => notify('Ad drill-down is represented in campaign details.')}>Ads</button></div></header><div className="db-toolbar compact"><label className="db-toolbar-search"><Icon name="search" size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search campaigns…" /></label><Field label="Status"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="learning">Learning</option><option value="paused">Paused</option><option value="completed">Completed</option></select></Field><Field label="Sort"><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="spend">Spend</option><option value="leads">Leads</option><option value="name">Name</option></select></Field></div><div className="db-table-wrap"><table className="db-table"><thead><tr><th>Campaign</th><th>Delivery</th><th>Budget</th><th>Spend</th><th>Leads</th><th>CPL</th><th>CTR</th><th aria-label="Actions" /></tr></thead><tbody>{visible.map((campaign) => <tr key={campaign.id}><td><button className="db-table-name" onClick={() => setDetail(campaign)}><CreativeArt palette={campaign.palette} theme={campaign.name.toUpperCase().replace(' ', ' / ')} compact /><span><b>{campaign.name}</b><small>{campaign.objective} · Updated {campaign.updated}</small></span></button></td><td><Badge tone={campaign.status === 'active' ? 'lime' : campaign.status === 'learning' ? 'blue' : campaign.status === 'paused' ? 'orange' : 'gray'}>{campaign.delivery}</Badge></td><td>${campaign.budget}/day</td><td>${campaign.spend.toLocaleString()}</td><td>{campaign.leads}</td><td>${campaign.cpl}</td><td>{campaign.ctr}%</td><td><button className="db-icon-action" onClick={() => toggle(campaign)} aria-label={campaign.status === 'paused' ? 'Resume' : 'Pause'}><Icon name={campaign.status === 'paused' ? 'play' : 'pause'} size={15} /></button><button className="db-icon-action" onClick={() => setDetail(campaign)} aria-label="Details"><Icon name="more" size={16} /></button></td></tr>)}</tbody></table></div>{!visible.length && <EmptyState icon="search" title="No matching campaigns" body="Adjust the search or status filter." />}</section></>}
    {detail && <Modal title={detail.name} onClose={() => setDetail(null)} wide footer={<><Button variant="ghost" onClick={() => setDetail(null)}>Close</Button><Button variant="secondary" icon={detail.status === 'paused' ? 'play' : 'pause'} onClick={() => toggle(detail)}>{detail.status === 'paused' ? 'Resume campaign' : 'Pause campaign'}</Button></>}><div className="db-campaign-detail"><div><CreativeArt palette={detail.palette} theme={detail.name.toUpperCase().replace(' ', ' / ')} /><AdPreview headline="Move with purpose this summer" primary="Made for mornings that turn into adventures. Meet the collection designed to move with you." palette={detail.palette} /></div><div><Badge tone={detail.status === 'active' ? 'lime' : 'orange'}>{detail.status}</Badge><h3>Performance snapshot</h3><div className="db-detail-metrics"><span><small>Spend</small><b>${detail.spend}</b></span><span><small>Leads</small><b>{detail.leads}</b></span><span><small>CPL</small><b>${detail.cpl}</b></span><span><small>CTR</small><b>{detail.ctr}%</b></span></div><div className="db-mini-bars">{[42, 58, 48, 66, 78, 72, 91, 85, 96, 88, 100, 94].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div><div className="db-form-grid two"><Field label="Daily budget"><input type="number" value={detail.budget} onChange={(event) => setDetail({ ...detail, budget: event.target.value })} /></Field><Field label="Status"><select value={detail.status} onChange={(event) => setDetail({ ...detail, status: event.target.value })}><option value="active">Active</option><option value="paused">Paused</option></select></Field></div><Button icon="check" onClick={() => { setItems((current) => current.map((item) => item.id === detail.id ? detail : item)); notify('Campaign changes saved.') }}>Save campaign</Button></div></div></Modal>}
  </div>
}

export function LeadsView({ connected, onManage, notify }) {
  const [leads, setLeads] = useState(leadRecords)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [detail, setDetail] = useState(null)
  const visible = leads.filter((lead) => (status === 'all' || lead.status === status) && `${lead.name} ${lead.email} ${lead.campaign}`.toLowerCase().includes(query.toLowerCase()))
  const setLeadStatus = (id, next) => { setLeads((current) => current.map((lead) => lead.id === id ? { ...lead, status: next } : lead)); setDetail((current) => current?.id === id ? { ...current, status: next } : current) }
  const download = () => { const rows = [['Name', 'Email', 'Phone', 'Campaign', 'Status', 'Received'], ...leads.map((lead) => [lead.name, lead.email, lead.phone, lead.campaign, lead.status, lead.received])]; const blob = new Blob([rows.map((row) => row.join(',')).join('\n')], { type: 'text/csv' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'adcraft-leads.csv'; link.click(); URL.revokeObjectURL(link.href); notify('Lead CSV prepared.') }
  return <div className="db-page"><PageIntro eyebrow="Lead center" icon="leads" title="Turn form fills into conversations." description="Lead-form submissions from Meta, organized for quick follow-up." actions={<><Button variant="secondary" icon="refresh" onClick={() => notify('Lead sync complete.')}>Sync leads</Button><Button icon="download" onClick={download}>Export CSV</Button></>} /><MetaAccountStrip connected={connected} onManage={onManage} />
    {!connected ? <EmptyState icon="leads" title="Connect Meta to receive leads" body="Lead delivery and Page subscriptions are configured from Connections." /> : <><div className="db-metric-grid four"><article className="db-card"><span>Total leads</span><strong>{leads.length}</strong><small>Last 14 days</small></article><article className="db-card"><span>New</span><strong>{leads.filter((item) => item.status === 'new').length}</strong><small>Needs follow-up</small></article><article className="db-card"><span>Qualified</span><strong>{leads.filter((item) => item.status === 'qualified').length}</strong><small className="good">33% qualification rate</small></article><article className="db-card"><span>Average response</span><strong>18m</strong><small>12m faster this week</small></article></div><section className="db-card db-data-section"><header><div><h2>Leads from ads</h2><p>Synced from your selected Facebook Page and Meta webhook.</p></div><Badge tone="blue">Lead delivery active</Badge></header><div className="db-toolbar compact"><label className="db-toolbar-search"><Icon name="search" size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search leads…" /></label><Field label="Status"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="closed">Closed</option></select></Field></div><div className="db-table-wrap"><table className="db-table leads"><thead><tr><th>Lead</th><th>Contact</th><th>Campaign</th><th>Timeline</th><th>Status</th><th>Received</th></tr></thead><tbody>{visible.map((lead) => <tr key={lead.id}><td><button className="db-lead-name" onClick={() => setDetail(lead)}><span>{lead.name.split(' ').map((word) => word[0]).join('')}</span><b>{lead.name}</b></button></td><td><span>{lead.email}</span><small>{lead.phone}</small></td><td><b>{lead.campaign}</b><small>{lead.source}</small></td><td>{lead.timeline}</td><td><select className={`db-status-select ${lead.status}`} value={lead.status} onChange={(event) => { setLeadStatus(lead.id, event.target.value); notify('Lead status updated.') }}><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="closed">Closed</option></select></td><td>{lead.received}</td></tr>)}</tbody></table></div>{!visible.length && <EmptyState icon="search" title="No matching leads" body="Try another status or search term." />}</section></>}
    {detail && <Modal title={detail.name} onClose={() => setDetail(null)} footer={<><Button variant="ghost" onClick={() => setDetail(null)}>Close</Button><Button icon="check" onClick={() => { setLeadStatus(detail.id, detail.status); setDetail(null); notify('Lead updated.') }}>Save lead</Button></>}><div className="db-lead-detail"><span className="db-lead-avatar">{detail.name.split(' ').map((word) => word[0]).join('')}</span><Badge tone={detail.status === 'qualified' ? 'lime' : detail.status === 'new' ? 'blue' : 'gray'}>{detail.status}</Badge><h3>{detail.name}</h3><a href={`mailto:${detail.email}`}><Icon name="mail" size={15} />{detail.email}</a><a href={`tel:${detail.phone}`}><Icon name="phone" size={15} />{detail.phone}</a><dl><div><dt>Campaign</dt><dd>{detail.campaign}</dd></div><div><dt>Placement</dt><dd>{detail.source}</dd></div><div><dt>Purchase timeline</dt><dd>{detail.timeline}</dd></div><div><dt>Received</dt><dd>{detail.received}</dd></div></dl><Field label="Lead status"><select value={detail.status} onChange={(event) => setDetail({ ...detail, status: event.target.value })}><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="closed">Closed</option></select></Field><Field label="Internal note"><textarea rows="4" placeholder="Add context for the next follow-up…" /></Field></div></Modal>}
  </div>
}

export function OptimizeView({ connected, onManage, notify }) {
  const [recommendations, setRecommendations] = useState(optimizationRecommendations)
  const [history, setHistory] = useState(optimizationHistory)
  const [mode, setMode] = useState('review')
  const [busy, setBusy] = useState(false)
  const [settings, setSettings] = useState({ target: 10, change: 20, min: 10, hour: 2, budgets: true, pause: true, creative: true, audience: false })
  const [folderOpen, setFolderOpen] = useState(false)
  const selected = recommendations.filter((item) => item.selected)
  const apply = async (items = selected) => { if (!items.length) return; setBusy(true); await dashboardMockService.applyOptimizations(items.map((item) => item.id)); setRecommendations((current) => current.filter((item) => !items.some((selectedItem) => selectedItem.id === item.id))); setHistory((current) => [...items.map((item, index) => ({ id: Date.now() + index, action: item.title, target: 'Selected account', by: 'Alex Morgan', date: 'Just now', undone: false })), ...current]); setBusy(false); notify(`${items.length} optimization${items.length === 1 ? '' : 's'} applied.`) }
  return <div className="db-page"><PageIntro eyebrow="Account optimization" icon="optimize" title="Make every learning count." description="Review evidence-backed recommendations or let guarded automation handle routine changes." /><MetaAccountStrip connected={connected} onManage={onManage} />
    {!connected ? <EmptyState icon="optimize" title="No account to optimize" body="Connect Meta Ads to calculate account-level recommendations." /> : <><section className="db-optimize-hero db-card"><div><span className="db-eyebrow"><Icon name="spark" size={14} /> Optimize for me</span><h2>4 opportunities found across 3 campaigns.</h2><p>Recommendations use delivery, cost, frequency, and creative fatigue from the selected period.</p></div><div className="db-mode-switch"><button className={mode === 'review' ? 'active' : ''} onClick={() => setMode('review')}>Review first</button><button className={mode === 'auto' ? 'active' : ''} onClick={() => setMode('auto')}>Hands-free</button></div></section><div className="db-scope-bar db-card"><span><Icon name="folder" size={15} /> Scope</span><button className="active">Whole account</button><button>Growth campaigns</button><button>Launches</button><Button variant="ghost" icon="plus" onClick={() => setFolderOpen(true)}>Folder</Button></div>
      <div className="db-optimize-layout"><section className="db-card db-recommendation-panel"><header><div><h2>Review queue</h2><p>Choose exactly which changes Adcraft can apply.</p></div><Badge tone="blue">{recommendations.length} ready</Badge></header>{recommendations.length ? <div className="db-recommendation-list">{recommendations.map((item) => <article className={item.selected ? 'selected' : ''} key={item.id}><button className="db-select-check" onClick={() => setRecommendations((current) => current.map((record) => record.id === item.id ? { ...record, selected: !record.selected } : record))}>{item.selected && <Icon name="check" size={13} />}</button><span className={`db-rec-icon ${item.type}`}><Icon name={item.type === 'budget' ? 'wallet' : item.type === 'pause' ? 'pause' : item.type === 'creative' ? 'image' : 'target'} size={18} /></span><div><Badge tone={item.confidence === 'High' ? 'lime' : 'blue'}>{item.confidence} confidence</Badge><h3>{item.title}</h3><p>{item.body}</p><strong>{item.impact}</strong></div><Button variant="soft" onClick={() => apply([item])}>Apply</Button></article>)}</div> : <EmptyState icon="check" title="Queue cleared" body="No more changes are recommended for this scope." />}<footer><Button variant="secondary" onClick={() => setRecommendations((current) => current.map((item) => ({ ...item, selected: true })))}>Select all</Button><Button icon="check" disabled={!selected.length || busy} onClick={() => apply()}>{busy ? 'Applying…' : `Apply selected (${selected.length})`}</Button></footer></section>
      <aside className="db-automation-panel"><section className="db-card"><div className="db-card-title"><div><span><Icon name="bolt" size={15} /></span><h3>Automation settings</h3></div><Button variant="soft" icon="check" onClick={() => notify('Automation settings saved.')}>Save</Button></div><div className="db-form-grid two"><Field label="Target CPL"><input type="number" value={settings.target} onChange={(event) => setSettings({ ...settings, target: event.target.value })} /></Field><Field label="Max budget change %"><input type="number" value={settings.change} onChange={(event) => setSettings({ ...settings, change: event.target.value })} /></Field><Field label="Minimum daily budget"><input type="number" value={settings.min} onChange={(event) => setSettings({ ...settings, min: event.target.value })} /></Field><Field label="Run hour (UTC)"><input type="number" min="0" max="23" value={settings.hour} onChange={(event) => setSettings({ ...settings, hour: event.target.value })} /></Field></div><div className="db-automation-toggles"><Toggle checked={settings.budgets} onChange={(value) => setSettings({ ...settings, budgets: value })} label="Budget pacing" hint="Scale strong ad sets within guardrails." /><Toggle checked={settings.pause} onChange={(value) => setSettings({ ...settings, pause: value })} label="Waste control" hint="Pause ads after enough evidence." /><Toggle checked={settings.creative} onChange={(value) => setSettings({ ...settings, creative: value })} label="Fatigue alerts" hint="Watch frequency and CTR decline." /><Toggle checked={settings.audience} onChange={(value) => setSettings({ ...settings, audience: value })} label="Audience expansion" hint="Test adjacent audience segments." /></div></section></aside></div>
      <section className="db-card db-history"><header><div><h2>Change history</h2><p>Applied actions remain visible and reversible when supported.</p></div></header>{history.map((item) => <div key={item.id}><span><Icon name="bolt" size={15} /></span><div><b>{item.action}</b><p>{item.target} · {item.date} · {item.by}</p></div>{item.undone ? <Badge tone="gray">Undone</Badge> : <Button variant="ghost" icon="undo" onClick={() => { setHistory((current) => current.map((entry) => entry.id === item.id ? { ...entry, undone: true } : entry)); notify('Optimization change undone.') }}>Undo</Button>}</div>)}</section></>}
    {folderOpen && <Modal title="New optimization folder" onClose={() => setFolderOpen(false)} footer={<><Button variant="ghost" onClick={() => setFolderOpen(false)}>Cancel</Button><Button icon="check" onClick={() => { setFolderOpen(false); notify('Optimization folder saved.') }}>Save folder</Button></>}><div className="db-modal-form"><Field label="Folder name"><input defaultValue="Priority campaigns" /></Field><Field label="Daily spend cap"><input type="number" defaultValue="150" /></Field><Field label="Target cost per lead"><input type="number" defaultValue="10" /></Field><Field label="Campaigns"><div className="db-checkbox-list">{campaigns.slice(0, 3).map((item) => <label key={item.id}><input type="checkbox" defaultChecked /> {item.name}</label>)}</div></Field></div></Modal>}
  </div>
}

export function AdsLibraryView({ connected, onManage, notify, onGo }) {
  const input = useRef(null)
  const [assets, setAssets] = useState(assetLibrary)
  const [templates, setTemplates] = useState(campaignTemplates)
  const [folder, setFolder] = useState('All')
  const folders = ['All', ...new Set(assets.map((item) => item.folder))]
  const visible = folder === 'All' ? assets : assets.filter((item) => item.folder === folder)
  const upload = (file) => { if (!file) return; setAssets((current) => [{ id: `asset-${Date.now()}`, name: file.name, folder: 'Uploads', kind: 'Uploaded', palette: 'mono', theme: 'NEW / ASSET', imageUrl: URL.createObjectURL(file) }, ...current]); notify('Creative added to the demo asset library.') }
  return <div className="db-page"><PageIntro eyebrow="Creative library" icon="library" title="Reuse the work that already works." description="Campaign templates, generated visuals, uploads, and recent launch records." actions={<Button icon="upload" onClick={() => input.current?.click()}>Upload asset</Button>} /><input ref={input} type="file" accept="image/*" hidden onChange={(event) => upload(event.target.files?.[0])} /><MetaAccountStrip connected={connected} onManage={onManage} />
    {!connected ? <EmptyState icon="library" title="Connect Meta to load the library" body="Generated campaign assets and templates are stored against your connected workspace." /> : <><section className="db-card db-template-section"><header><div><h2>Campaign templates</h2><p>Saved plans include copy, images, targeting, lead form, and budget.</p></div><Badge tone="blue">{templates.length} templates</Badge></header><div className="db-template-grid">{templates.map((template) => <article key={template.id}><span><Icon name="copy" size={19} /></span><Badge tone="gray">{template.uses} uses</Badge><h3>{template.name}</h3><p>{template.description}</p><div><small>{template.copies} copy angles</small><small>{template.images} images</small><small>${template.budget}/day</small></div><footer><Button variant="soft" icon="play" onClick={() => { notify(`Using “${template.name}” in Campaign Studio.`); onGo('adstudio') }}>Use template</Button><button onClick={() => setTemplates((current) => current.filter((item) => item.id !== template.id))} aria-label="Delete template"><Icon name="trash" size={15} /></button></footer></article>)}</div></section>
      <section className="db-card db-asset-section"><header><div><h2>Asset library</h2><p>Generated and uploaded creative, organized into reusable folders.</p></div><Button variant="secondary" icon="upload" onClick={() => input.current?.click()}>Upload</Button></header><div className="db-folder-pills">{folders.map((name) => <button className={folder === name ? 'active' : ''} onClick={() => setFolder(name)} key={name}><Icon name="folder" size={13} />{name}<span>{name === 'All' ? assets.length : assets.filter((item) => item.folder === name).length}</span></button>)}</div>{visible.length ? <div className="db-asset-grid">{visible.map((asset) => <article key={asset.id}><CreativeArt palette={asset.palette} theme={asset.theme} imageUrl={asset.imageUrl} compact /><div><b>{asset.name}</b><Badge tone="gray">{asset.kind}</Badge><Field label="Folder"><select value={asset.folder} onChange={(event) => setAssets((current) => current.map((item) => item.id === asset.id ? { ...item, folder: event.target.value } : item))}>{folders.filter((item) => item !== 'All').map((name) => <option key={name}>{name}</option>)}<option>Uploads</option></select></Field><button onClick={() => { setAssets((current) => current.filter((item) => item.id !== asset.id)); notify('Asset deleted.') }}><Icon name="trash" size={15} /> Delete</button></div></article>)}</div> : <EmptyState icon="image" title="No assets in this folder" body="Choose another folder or upload a new creative." />}</section>
      <section className="db-card db-launch-records"><header><div><h2>Recent launches</h2><p>Campaigns created from Adcraft’s Campaign Studio.</p></div></header><div className="db-table-wrap"><table className="db-table"><thead><tr><th>Campaign</th><th>Offer</th><th>Status</th><th>Ads</th><th>Template</th><th>Created</th></tr></thead><tbody><tr><td><b>Summer Movement</b></td><td>Summer collection</td><td><Badge>Active</Badge></td><td>4</td><td>Product launch sprint</td><td>Sep 25</td></tr><tr><td><b>Studio Consultation</b></td><td>Strategy call</td><td><Badge tone="gray">Paused</Badge></td><td>2</td><td>Consultation bookings</td><td>Sep 18</td></tr></tbody></table></div></section></>}
  </div>
}
